config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  root to: 'homes#top'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "creating successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
    
      # @book=Book.new
      render :index
    end
  end

  def index
    @books = Book.all
    # @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path
    else
      flash[:alert] = "Updating error."
      redirect_to book_path
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed"
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", "/books" %>

app/views/books/index.html.erb
<h1><b>Books</b></h1>

<table>
  <thead>
    <th><b>Title</b></th>
    <th><b>Body</b></th>
    <th colspan="3"></th>
  </thead>

  <tbody>
    <%  @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to 'Show', book_path(book.id) %></td>
      <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
      <td><%= link_to 'Destroy', destroy_book_path(book.id), method: :delete, "data-confirm" =>"Are you sure?" %></td>
   </tr>
   <% end %>
  </tbody>
</table>


<h2><b>New book</b></h2>

    <% if @book && @book.errors.any? %>
      <div class = "error_message">
        <ul>
          <%= @book.errors.count %>error(s) occoured.
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

<%= form_with model: Book.new, url:'/books', local:true do |f| %>

  <h4>Title</h4>
  <span><%= f.text_field :title %></span>

  <h4>Body</h4>
  <span><%= f.text_area :body %></span>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>
<!-- form_with部分 -->
<%= form_with model: @book, url:'/books', local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'create new book' %>
<% end %>

app/views/books/show.html.erb
<div class="container spa1">
    <p><b>Title:</b><p>
    <p><%= @book.title %></p>
</div>
<div class="container spa1">
    <p><b>Body:</b></p>
    <p><%= @book.body %></p>
</div>
<div class="container spa2">
    <p><%= link_to "Edit", edit_book_path(@book.id) %></p>
    <p>|</p>
    <p><%= link_to "Back", books_path %></p>
</div>

app/views/homes/top.html.erb
<h1><b>ようこそ Bookers へ!</b></h1>
<div class="spa1">
  <p><b>Bookers</b>では、様々な書籍に関するあなたの意見や<br>印象を共有し交換することができます。</p>
  <span>
    <%= link_to 'start', "/books" %>
  </span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <p id="notice"><%= notice %></p>
   <p id="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>